kind: BuildConfig
apiVersion: v1
metadata:
  name: spring-gitflow-pipeline
  labels:
    app: sprin-gitflow
spec:
  resources:
    requests:
      cpu: 2000Mi
      memory: 1G
  source:
    git:
      ref: master
      uri: "https://github.com/sudheej/jenkins-gitflow-pipeline-openshift.git"
    type: Git
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
