kind: BuildConfig
apiVersion: v1
metadata:
  name: spring-boot-demo-pipeline
  labels:
    app: spring-boot-demo
spec:
  resources:
    requests:
      cpu: 2000Mi
      memory: 1G
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
